{% set name = "tbvcfreport" %}
{% set version = "0.0.5" %}
{% set sha256 = "6a62748ac8f4f8f4ee2d141ce8cb29f06c7a971aaabaaedcaa8fa5220aaf2410" %}
{% set py2neo = "4.0.0" %}
{% set pyvcf = "0.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('VERSION', None) or version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/COMBAT-TB/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ environ.get('SHA', None) or sha256 }}

build:
  script_env:
    - SHA
    - VERSION
    - CONDA_BLD_PATH
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - click
    - jinja2
    - py2neo {{ py2neo }}
    - pyvcf {{ pyvcf }}
    - tqdm
  run:
    - python
    - click
    - jinja2
    - py2neo {{ py2neo }}
    - pyvcf {{ pyvcf }}
    - tqdm

test:
  imports:
    - tbvcfreport
  commands:
    - tbvcfreport generate --help 2>&1 |grep VCF_DIR >/dev/null

about:
  home: https://github.com/COMBAT-TB/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Generate a report on M. tuberculosis variants with links to Combat TB Explorer database'
