{% set name = "tb-vcf-report" %}
{% set version = "0.0.1" %}
{% set sha256 = "46dd5e7578bf79b7c4e124a75f92d4468443ed692e038ddf23d4dfd07fee145a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/COMBAT-TB/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - click
    - jinja2
    - py2neo 3.1.2
    - pyvcf 0.6.8
    - tqdm
  run:
    - python
    - click
    - jinja2
    - py2neo 3.1.2
    - pyvcf 0.6.8
    - tqdm

test:
  imports:
    - tbvcfreport
  commands:
    - tbvcfreport generate --help 2>&1 |grep VCF_DIR >/dev/null

about:
  home: https://github.com/COMBAT-TB/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Generate a report on M. tuberculosis variants with links to Combat TB Explorer database'
