{% set version = "0.0.6" %}
{% set sha256 = "06fe33fef173af5292171606105f112409446137df2519770d6c8d0370b76023" %}
{% set py2neo = "4.2.0" %}
{% set pyvcf = "0.6.8" %}

package:
  name: tbvcfreport
  version: {{ version }}

source:
  url: https://github.com/COMBAT-TB/tbvcfreport/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python -m pip install --no-deps --ignore-installed .
  number: 0


requirements:
  build:
    - python
    - pip
    - click
    - jinja2
    - py2neo {{ py2neo }}
    - pyvcf {{ pyvcf }}
    - tqdm
  run:
    - python
    - click
    - jinja2
    - py2neo {{ py2neo }}
    - pyvcf {{ pyvcf }}
    - tqdm

test:
  imports:
    - tbvcfreport
  commands:
    - tbvcfreport generate --help 2>&1 |grep VCF_DIR >/dev/null

about:
  home: https://github.com/COMBAT-TB/tbvcfreport
  license_file: LICENSE
  summary: 'Builds an HTML based report on SnpEff generated M. tuberculosis variant file'
  dev_url: https://github.com/COMBAT-TB/tbvcfreport
