{% set version = "0.1.7" %}
{% set sha256 = "7a106d48c19dda4998c956ce358c9d90e82e80bb105757d1ab039808060c9673" %}
{% set py2neo = "4.2.0" %}

package:
  name: tbvcfreport
  version: {{ version }}

source:
  url: https://github.com/COMBAT-TB/tbvcfreport/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python -m pip install --no-deps --ignore-installed .
  number: 0


requirements:
  host:
    - python
    - pip
    - click
    - jinja2
    - py2neo {{ py2neo }}
    - pyvcf
    - tqdm
  run:
    - python
    - click
    - jinja2
    - py2neo {{ py2neo }}
    - pyvcf
    - tqdm
    - mtb-snp-it

test:
  imports:
    - tbvcfreport
  commands:
    - tbvcfreport generate --help 2>&1 |grep VCF_DIR >/dev/null

about:
  home: https://github.com/COMBAT-TB/tbvcfreport
  license_file: LICENSE
  summary: 'Generates an interactive HTML report on SnpEff annotated M.tb VCF(s)'
  dev_url: https://github.com/COMBAT-TB/tbvcfreport
