{% set version = "0.1.5" %}
{% set sha256 = "0517db5c37e9a110491626623f36c7d03a004818339deeb79df1049bd133d26a" %}
{% set py2neo = "4.2.0" %}

package:
  name: tbvcfreport
  version: {{ version }}

source:
  url: https://github.com/COMBAT-TB/tbvcfreport/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python -m pip install --no-deps --ignore-installed .
  number: 0


requirements:
  host:
    - python
    - pip
    - click
    - jinja2
    - py2neo {{ py2neo }}
    - pyvcf
    - tqdm
  run:
    - python
    - click
    - jinja2
    - py2neo {{ py2neo }}
    - pyvcf
    - tqdm
    - mtb-snp-it

test:
  imports:
    - tbvcfreport
  commands:
    - tbvcfreport generate --help 2>&1 |grep VCF_DIR >/dev/null

about:
  home: https://github.com/COMBAT-TB/tbvcfreport
  license_file: LICENSE
  summary: 'Builds an HTML based report on SnpEff generated M. tuberculosis variant file'
  dev_url: https://github.com/COMBAT-TB/tbvcfreport
